# Generated by Django 2.2.10 on 2020-02-22 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_on_delete_set_null'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['submission_date', 'title'], 'verbose_name': 'Task', 'verbose_name_plural': 'Tasks'},
        ),
        migrations.AlterField(
            model_name='task',
            name='all_checker_finished',
            field=models.BooleanField(default=False, editable=False, help_text="Indicates whether the checker which don't run immediately on submission have been executed.", verbose_name='All checker finished'),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(help_text='Description of the assignment.', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='final_grade_rating_scale',
            field=models.ForeignKey(help_text='The scale used to mark the whole solution.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='attestation.RatingScale', verbose_name='Final grade rating scale'),
        ),
        migrations.AlterField(
            model_name='task',
            name='jplag_up_to_date',
            field=models.BooleanField(default=False, help_text='No new solution uploads since the last jPlag run', verbose_name='JPlag up to date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='max_file_size',
            field=models.IntegerField(default=1000, help_text='The maximum size of an uploaded solution file in kilobyte.', verbose_name='Max file size'),
        ),
        migrations.AlterField(
            model_name='task',
            name='model_solution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='model_solution_task', to='solutions.Solution', verbose_name='Model Solution'),
        ),
        migrations.AlterField(
            model_name='task',
            name='only_trainers_publish',
            field=models.BooleanField(default=False, help_text='Indicates that only trainers may publish attestations. Otherwise, tutors may publish final attestations within their tutorials.', verbose_name='only trainers publish'),
        ),
        migrations.AlterField(
            model_name='task',
            name='publication_date',
            field=models.DateTimeField(help_text='The time on which the user will see the task.', verbose_name='Publication Date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='submission_date',
            field=models.DateTimeField(help_text='The time up until the user has time to complete the task. This time will be extended by one hour for those who just missed the deadline.', verbose_name='Submission date'),
        ),
        migrations.AlterField(
            model_name='task',
            name='supported_file_types',
            field=models.CharField(default='^(text/.*|image/.*|application/pdf)$', help_text='Regular Expression describing the mime types of solution files that the user is allowed to upload.', max_length=1000, verbose_name='Supported file types'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(help_text='The name of the task', max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='task',
            name='warning_threshold',
            field=models.DecimalField(decimal_places=2, default=0, help_text='If the student has less points in his tasks than the sum of their warning thresholds, display a warning.', max_digits=8, verbose_name='Warning threshold'),
        ),
    ]
