# Generated by Django 2.2.10 on 2020-03-10 13:26

from django.db import migrations, models
import tasks.models
import utilities.deleting_file_field


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20200222_1942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='htmlinjector',
            options={'verbose_name': 'HTML Injector', 'verbose_name_plural': 'HTML Injectors'},
        ),
        migrations.AlterModelOptions(
            name='mediafile',
            options={'verbose_name': 'Media File', 'verbose_name_plural': 'Media Files'},
        ),
        migrations.AlterField(
            model_name='htmlinjector',
            name='html_file',
            field=utilities.deleting_file_field.DeletingFileField(max_length=500, upload_to=tasks.models.get_htmlinjectorfile_storage_path, verbose_name='HTML File'),
        ),
        migrations.AlterField(
            model_name='htmlinjector',
            name='inject_in_attestation_edit',
            field=models.BooleanField(default=True, help_text='Indicates whether HTML code shall be injected in attestation edits, e.g.: in https://praktomat.cs.kit.edu/2016_WS_Abschluss/attestation/134/edit', verbose_name='inject in attestation edit'),
        ),
        migrations.AlterField(
            model_name='htmlinjector',
            name='inject_in_attestation_view',
            field=models.BooleanField(default=False, help_text='Indicates whether HTML code shall be injected in attestation views, e.g.: in https://praktomat.cs.kit.edu/2016_WS_Abschluss/attestation/134', verbose_name='inject in attestation view'),
        ),
        migrations.AlterField(
            model_name='htmlinjector',
            name='inject_in_solution_full_view',
            field=models.BooleanField(default=False, help_text='Indicates whether HTML code shall be injected in private solution views, e.g.: in https://praktomat.cs.kit.edu/2016_WS_Abschluss/solutions/5710/full', verbose_name='inject in solution full view'),
        ),
        migrations.AlterField(
            model_name='htmlinjector',
            name='inject_in_solution_view',
            field=models.BooleanField(default=False, help_text='Indicates whether HTML code shall be injected in public  solution views, e.g.: in https://praktomat.cs.kit.edu/2016_WS_Abschluss/solutions/5710/', verbose_name='inject in solution view'),
        ),
        migrations.AlterField(
            model_name='mediafile',
            name='media_file',
            field=utilities.deleting_file_field.DeletingFileField(max_length=500, upload_to=tasks.models.get_mediafile_storage_path, verbose_name='Media File'),
        ),
    ]
