# Generated by Django 2.2.10 on 2020-02-22 19:42

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_custom_user_text'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tutorial',
            options={'verbose_name': 'Tutorial', 'verbose_name_plural': 'Tutorials'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['first_name', 'last_name'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
        migrations.AlterField(
            model_name='user',
            name='final_grade',
            field=models.CharField(blank=True, help_text='The final grade for the whole class.', max_length=100, null=True, verbose_name='Final Grade'),
        ),
        migrations.AlterField(
            model_name='user',
            name='mat_number',
            field=models.IntegerField(blank=True, null=True, validators=[accounts.models.validate_mat_number], verbose_name='Mat number'),
        ),
        migrations.AlterField(
            model_name='user',
            name='programme',
            field=models.CharField(blank=True, help_text='The programme the student is enlisted in.', max_length=100, null=True, verbose_name='Programme'),
        ),
        migrations.AlterField(
            model_name='user',
            name='tutorial',
            field=models.ForeignKey(blank=True, help_text='The tutorial the student belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Tutorial', verbose_name='Tutorial'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_text',
            field=models.CharField(blank=True, help_text='Custom text which will be shown to this student.', max_length=500, null=True, verbose_name='User text'),
        ),
    ]
