# Generated by Django 2.2.10 on 2020-07-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200222_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='accepted_disclaimer',
            field=models.BooleanField(default=False, help_text='Whether the user accepted the disclaimer.', verbose_name='Accept disclaimer'),
        ),
    ]
