# Generated by Django 2.2.10 on 2020-02-22 19:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0009_auto_20190408_1427'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chunk',
            options={'verbose_name': 'Chunk', 'verbose_name_plural': 'Chunks'},
        ),
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Setting', 'verbose_name_plural': 'Settings'},
        ),
        migrations.AlterField(
            model_name='chunk',
            name='content',
            field=models.TextField(blank=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='accept_all_solutions',
            field=models.BooleanField(default=False, help_text='If enabled, solutions can become the final soution even if not all required checkers are passed.', verbose_name='Accept all solutions'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='account_manual_validation',
            field=models.BooleanField(default=False, help_text='If enabled, registrations via the website must be manually validated by a trainer.', verbose_name='Account manual validation'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='acount_activation_days',
            field=models.IntegerField(default=10, help_text='Days until the user has time to activate his account with the link sent in the registration email.', verbose_name='Account activation days'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='anonymous_attestation',
            field=models.BooleanField(default=False, help_text="If enabled, the tutor can't see the name of the user who submitted the solution.", verbose_name='Anonymous attestation'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='attestation_allow_run_checkers',
            field=models.BooleanField(default=False, help_text='If enabled, tutors can re-run all checkers for solutions they attest. Can be used to re-run checks that failed due to problems unrelated to the solution (e.g.: time-outs because of high server load), but needs to be used with care, since it may change the results from what the student saw when he submitted his solution.', verbose_name='Attestation allow run checkers'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='attestation_reply_to',
            field=models.EmailField(blank=True, help_text='Additional Reply-To: address to be set for attestation emails.', max_length=254, verbose_name='Attestation Reply-To'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='deny_registration_from',
            field=models.DateTimeField(default=datetime.date(2222, 1, 1), help_text="After this date, registration won't be possible.", verbose_name='Deny registration from'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='email_validation_regex',
            field=models.CharField(blank=True, default='.*@(stud.)?fra-uas.de', help_text='Regular expression used to check the email domain of registering users.', max_length=200, verbose_name='Email validation regex'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='final_grades_arithmetic_option',
            field=models.CharField(choices=[('SUM', 'Sum'), ('AVG', 'Average')], default='SUM', max_length=3, verbose_name='Final grades arithmetic option'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='final_grades_plagiarism_option',
            field=models.CharField(choices=[('NP', 'Without'), ('WP', 'Including')], default='NP', max_length=2, verbose_name='Final grades plagiarism option'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='final_grades_published',
            field=models.BooleanField(default=False, help_text='If enabled, all users can see their final grades.', verbose_name='Finale grades published'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='invisible_attestor',
            field=models.BooleanField(default=False, help_text='If enabled, a user will not learn which tutor wrote attestations to his solutions. In particular, tutors will not be named in attestation emails.', verbose_name='Invisible attestor'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='mat_number_validation_regex',
            field=models.CharField(blank=True, default='\\d{5,7}', help_text='Regular expression used to check the student number.', max_length=200, verbose_name='Mat number validation regex'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='new_users_via_sso',
            field=models.BooleanField(default=True, help_text='If enabled, users previously unknown to the Praktomat can register via single sign on (eg. Shibboleth).', verbose_name='New user via sso'),
        ),
    ]
