# Generated by Django 2.2.10 on 2020-07-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0010_auto_20200222_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='requires_disclaimer_acceptance',
            field=models.BooleanField(default=False, help_text='If enabled, users have to accept the disclaimer before using the site.'),
        ),
    ]
