##from checker.tests.InterfaceChecker import Interface # re-enable with with availability of nested inlines. see interface checker
__all__ = [
    "AnonymityChecker",
    "LineWidthChecker",
    "LineCounter",
    "TextChecker",
    "InterfaceChecker", ##"Interface",
    "CreateFileChecker",
    "KeepFileChecker",
    "ScriptChecker",
    "DejaGnu",
    "CheckStyleChecker",
    "JUnitChecker",
    #"IsabelleChecker",
    #"HaskellTestFrameWorkChecker",
    #"RChecker",
    "CUnitChecker_v2",
    "DiffChecker",
    #"JavaChecker",
]
