# Generated by Django 2.2.10 on 2020-02-22 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solutions', '0006_remove_tar_support'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solution',
            options={'verbose_name': 'Solution', 'verbose_name_plural': 'Solutions'},
        ),
        migrations.AlterField(
            model_name='solution',
            name='accepted',
            field=models.BooleanField(default=False, help_text='Indicates whether the solution has passed all public and required tests.', verbose_name='Accepted'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creation Date'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='final',
            field=models.BooleanField(default=False, help_text='Indicates whether this solution is the last (accepted) of the author.', verbose_name='Final'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='plagiarism',
            field=models.BooleanField(default=False, help_text='Indicates whether the solution is a rip-off of another one.', verbose_name='Plagiarism'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Task', verbose_name='Task'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='testupload',
            field=models.BooleanField(default=False, help_text='Indicates whether this solution is a test upload.', verbose_name='Testupload'),
        ),
        migrations.AlterField(
            model_name='solution',
            name='warnings',
            field=models.BooleanField(default=False, help_text='Indicates whether the solution has at least failed one public and not required test.', verbose_name='Warnings'),
        ),
    ]
