# Generated by Django 2.2.10 on 2020-02-22 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attestation', '0006_limit_choices_to'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attestation',
            options={'verbose_name': 'Attestation', 'verbose_name_plural': 'Attestations'},
        ),
        migrations.AlterModelOptions(
            name='ratingscale',
            options={'verbose_name': 'Rating Scale', 'verbose_name_plural': 'Rating Scales'},
        ),
        migrations.AlterField(
            model_name='ratingaspect',
            name='description',
            field=models.TextField(help_text='Description of the Aspect and how it should be rated. E.w.: "How well is the code structured?"', verbose_name='Description'),
        ),
    ]
