# Generated by Django 2.2.10 on 2020-03-10 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attestation', '0007_auto_20200222_1942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annotatedsolutionfile',
            options={'verbose_name': 'Annotated solution file', 'verbose_name_plural': 'Annotated solution files'},
        ),
        migrations.AlterModelOptions(
            name='rating',
            options={'verbose_name': 'Rating', 'verbose_name_plural': 'Ratings'},
        ),
        migrations.AlterModelOptions(
            name='ratingaspect',
            options={'verbose_name': 'Rating Aspect', 'verbose_name_plural': 'Rating Aspects'},
        ),
        migrations.AlterModelOptions(
            name='ratingresult',
            options={'verbose_name': 'Rating result', 'verbose_name_plural': 'Rating results'},
        ),
        migrations.AlterModelOptions(
            name='script',
            options={'verbose_name': 'Script', 'verbose_name_plural': 'Scripts'},
        ),
        migrations.AlterField(
            model_name='attestation',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='created'),
        ),
        migrations.AlterField(
            model_name='attestation',
            name='final',
            field=models.BooleanField(default=False, help_text='Indicates whether the attestation is ready to be published', verbose_name='final'),
        ),
        migrations.AlterField(
            model_name='attestation',
            name='final_grade',
            field=models.ForeignKey(help_text='The mark for the whole solution.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='attestation.RatingScaleItem', verbose_name='Finale Grade'),
        ),
        migrations.AlterField(
            model_name='attestation',
            name='private_comment',
            field=models.TextField(blank=True, help_text='Comment which is only visible to tutors', verbose_name='Private Comment'),
        ),
        migrations.AlterField(
            model_name='attestation',
            name='public_comment',
            field=models.TextField(blank=True, help_text='Comment which is shown to the user.', verbose_name='Public Comment'),
        ),
        migrations.AlterField(
            model_name='attestation',
            name='published',
            field=models.BooleanField(default=False, help_text='Indicates whether the user can see the attestation.', verbose_name='published'),
        ),
        migrations.AlterField(
            model_name='attestation',
            name='published_on',
            field=models.DateTimeField(blank=True, help_text='The Date/Time the attestation was published.', null=True, verbose_name='published on'),
        ),
        migrations.AlterField(
            model_name='attestation',
            name='solution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='solutions.Solution', verbose_name='solution'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='aspect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attestation.RatingAspect', verbose_name='Rating Aspect'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='scale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attestation.RatingScale', verbose_name='Rating Scale'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.Task', verbose_name='Task'),
        ),
        migrations.AlterField(
            model_name='ratingresult',
            name='attestation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attestation.Attestation', verbose_name='Attestation'),
        ),
        migrations.AlterField(
            model_name='ratingresult',
            name='mark',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='attestation.RatingScaleItem', verbose_name='Rating Scale Item'),
        ),
        migrations.AlterField(
            model_name='ratingresult',
            name='rating',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attestation.Rating', verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='ratingscaleitem',
            name='scale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attestation.RatingScale', verbose_name='Rating Scale'),
        ),
    ]
